---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "nornir_files/hosts.yaml"
        group_file: "nornir_files/groups.yaml"
        defaults_file: "nornir_files/defaults.yaml"

runner:
    plugin: threaded
    options:
      num_workers: 2
